version: '3'

services:
  web:
    build: .
    command: gunicorn khalifa.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - media_file:/app/media
      - static_file:/app/static
    environment:
      - TZ=Asia/Tashkent

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - media_file:/app/media
      - static_file:/app/static
    depends_on:
      - web
    environment:
      - TZ=Asia/Tashkent

volumes:
  media_file:
  static_file: